### ISSUE TITLE
UIKit Missing from 12.0

### ISSUE THREAD

**Issue by RodBrown1988** [nst/iOS-Runtime-Headers#71]
@nst The latest commit for iOS 12.0 has removed UIKit from the Frameworks folder. I assume this is an oversight?

**Comment by DerekSelander** [comment]
A lot (all?) of the logic went to a private framework called UIKitCore for iOS 12 likely due to the macOS integration.  UIKit imports UIKitCore now in 12

**Comment by RodBrown1988** [comment]
Ah cool, my apologies

**Comment by liuaaaddxiaoer** [comment]
me too
