### ISSUE TITLE
doubt：What's this for?

### ISSUE THREAD

**Issue by Jacky-LinPeng** [nst/iOS-Runtime-Headers#79]
Can you tell me what these are for? Apple's official documentation is also available to view these header documents, right? So what's this for?

**Comment by xingheng** [comment]
No, they're exactly not the same, you could check out to local system and diff them. It's very useful to glance at the internal implementation, especially the private frameworks.

**Comment by Jacky-LinPeng** [comment]
感谢！ thanks

**Comment by Jacky-LinPeng** [comment]
> No, they're exactly not the same, you could check out to local system and diff them. It's very useful to glance at the internal implementation, especially the private frameworks.

thanks
